export const ALL_PERMISSIONS = [
  'products.view', 'products.create', 'products.update', 'products.delete',
  'products.import', 'products.export', 'products.categories.manage',
  'pos.access', 'pos.sales.create', 'pos.sales.hold', 'pos.sales.void',
  'pos.returns.create', 'pos.sales.view', 'pos.returns.process', 'pos.daily.close',
  'sales.view', 'sales.cancel', 'sales.void', 'sales.export',
  'sales.returns.view', 'sales.returns.approve', 'sales.email', 'sales.returns.create',
  'accounting.view', 'accounting.journals.create', 'accounting.accounts.manage',
  'accounting.reports', 'accounting.journals.reverse',
  'customers.view', 'customers.create', 'customers.update', 'customers.delete',
  'customers.export', 'customers.payments',
  'vendors.view', 'vendors.create', 'vendors.update', 'vendors.delete',
  'vendors.export', 'vendors.payments',
  'purchases.view', 'purchases.create', 'purchases.update',
  'purchases.receive', 'purchases.returns.create', 'purchases.returns.approve',
  'inventory.view', 'inventory.adjust', 'inventory.transfer',
  'inventory.movements', 'inventory.adjustments',
  'reports.view', 'reports.sales', 'reports.purchases',
  'reports.inventory', 'reports.financial', 'reports.export',
  'settings.view', 'settings.company', 'settings.pos', 'settings.notifications',
  'settings.backup', 'settings.update',
  'users.view', 'users.create', 'users.update', 'users.delete',
  'users.roles.manage', 'users.manage',
  'roles.view', 'roles.create', 'roles.update', 'roles.delete',
  'roles.permissions.manage', 'rbac.manage',
  'pricing-tiers.view', 'pricing-tiers.create', 'pricing-tiers.update', 'pricing-tiers.delete',
  'expenses.view', 'expenses.create', 'expenses.update', 'expenses.delete',
  'expenses.approve', 'expenses.pay', 'expenses.categories.manage',
  'loans.view', 'loans.manage',
  'notifications.view',
];

export const ALL_PERMISSIONS_SET = new Set(ALL_PERMISSIONS);
